#!/bin/bash

cd $GOPATH/src/github.com/letsencrypt/pebble
pebble -config ./test/config/pebble-config.json -dnsserver "127.0.0.1:10053"
# pebble -dnsserver 127.0.0.1:10053
# run dns01 --dir https://localhost:14000/dir --record 1.2.3.4 --domain netsec.ethz.ch
